spring:
  application:
    name: ordering
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration

algashop:
  integrations:
    shipping.provider: RAPIDEX

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
