spring:
  application:
    name: ordering
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: false
    locations: classpath:db/migration
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

algashop:
  integrations:
    shipping.provider: RAPIDEX
    rapidex:
      fallback:
        cost: "20.0"
        estimated-days: 10

management:
  info:
    env.enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db,readinessState
      status:
        order: "DOWN, OUT_OF_SERVICE, UNKNOWN, DEGRADED, UP"

info:
  app.name: AlgaShop Ordering API
